import { blankPixels, clampHeight, normalizeDocument, snapshotDocument, parseRgbaText, TRANSPARENT } from './model.js';
import { ModelRenderer } from './renderer3d.js';
import { exportGlb, exportObj } from './exporters.js';

const canvas = document.getElementById('pixelCanvas');
const ctx = canvas.getContext('2d');
const stage = document.getElementById('canvasStage');
const root = document.documentElement;
const modelRenderer = new ModelRenderer(document.getElementById('modelCanvas'));

const state = {
  width: 32, height: 32, pixels: [], color: '#E8ECF1FF', tool: 'pencil', drawMode: 'color', zoom: 16, grid: true, showHeightLabels: true,
  isDrawing: false, startCell: null, history: [], historyIndex: -1, dirty: false, geometry: 'voxel', modelOptions: { pixelSize: 1, heightScale: 1, gap: 0, base: false, baseThickness: 1 },
};
const toolNames = { pencil: '铅笔', eraser: '橡皮', fill: '填充', picker: '吸管', line: '直线', rect: '矩形' };

function normalizeColor(value) { let hex = String(value || '').trim().replace('#', '').toUpperCase(); if (hex.length === 3) hex = hex.split('').map((c) => c + c).join(''); if (hex.length === 6) hex += 'FF'; return /^[0-9A-F]{8}$/.test(hex) ? `#${hex}` : '#E8ECF1FF'; }
function colorToRgba(value) { const hex = normalizeColor(value).slice(1); return [0, 2, 4, 6].map((index) => parseInt(hex.slice(index, index + 2), 16)); }
function rgbaToHex(pixel) { return `#${pixel.slice(0, 4).map((value) => value.toString(16).padStart(2, '0')).join('').toUpperCase()}`; }
function sameColor(a, b) { return a[0] === b[0] && a[1] === b[1] && a[2] === b[2] && a[3] === b[3]; }
function cellIndex(x, y) { return y * state.width + x; }
function cellAt(x, y) { return state.pixels[cellIndex(x, y)]; }
function setCell(x, y, pixel) { if (x >= 0 && x < state.width && y >= 0 && y < state.height) state.pixels[cellIndex(x, y)] = [...pixel]; }
function currentDocument() { return { width: state.width, height: state.height, pixels: state.pixels }; }

function snapshot() { return snapshotDocument(currentDocument()); }
function restore(snap) { state.width = snap.width; state.height = snap.height; state.pixels = snap.pixels.map((pixel) => [...pixel]); syncSizeInputs(); draw(); updateModel(); updateUi(); }
function commitHistory() { state.history = state.history.slice(0, state.historyIndex + 1); state.history.push(snapshot()); if (state.history.length > 40) state.history.shift(); state.historyIndex = state.history.length - 1; state.dirty = true; updateHistoryButtons(); updateDirty(); }
function undo() { if (state.historyIndex <= 0) return; state.historyIndex -= 1; restore(state.history[state.historyIndex]); state.dirty = true; updateDirty(); }
function redo() { if (state.historyIndex >= state.history.length - 1) return; state.historyIndex += 1; restore(state.history[state.historyIndex]); state.dirty = true; updateDirty(); }

function draw() {
  ctx.clearRect(0, 0, canvas.width, canvas.height); const cellW = canvas.width / state.width; const cellH = canvas.height / state.height;
  for (let y = 0; y < state.height; y += 1) for (let x = 0; x < state.width; x += 1) {
    const pixel = cellAt(x, y); if (pixel[3]) { ctx.fillStyle = `rgba(${pixel[0]},${pixel[1]},${pixel[2]},${pixel[3] / 255})`; ctx.fillRect(x * cellW, y * cellH, cellW, cellH); }
    if (state.showHeightLabels && pixel[4] > 0) { ctx.fillStyle = state.drawMode === 'height' ? 'rgba(255,255,255,.92)' : 'rgba(20,24,28,.42)'; ctx.font = `${Math.max(8, Math.floor(cellW * .43))}px Consolas, monospace`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(String(pixel[4]), x * cellW + cellW / 2, y * cellH + cellH / 2); }
  }
  if (state.grid) { ctx.beginPath(); ctx.strokeStyle = 'rgba(91,99,108,.34)'; ctx.lineWidth = 1; for (let x = 0; x <= state.width; x += 1) { ctx.moveTo(Math.round(x * cellW) + .5, 0); ctx.lineTo(Math.round(x * cellW) + .5, canvas.height); } for (let y = 0; y <= state.height; y += 1) { ctx.moveTo(0, Math.round(y * cellH) + .5); ctx.lineTo(canvas.width, Math.round(y * cellH) + .5); } ctx.stroke(); }
  updatePixelCount(); updateLayerThumb();
}
function getCell(event) { const rect = canvas.getBoundingClientRect(); return { x: Math.max(0, Math.min(state.width - 1, Math.floor(((event.clientX - rect.left) / rect.width) * state.width))), y: Math.max(0, Math.min(state.height - 1, Math.floor(((event.clientY - rect.top) / rect.height) * state.height))) }; }
function lineCells(a, b) { const cells = []; let x = a.x; let y = a.y; const dx = Math.abs(b.x - a.x); const sx = a.x < b.x ? 1 : -1; const dy = -Math.abs(b.y - a.y); const sy = a.y < b.y ? 1 : -1; let err = dx + dy; while (true) { cells.push({ x, y }); if (x === b.x && y === b.y) break; const e2 = 2 * err; if (e2 >= dy) { err += dy; x += sx; } if (e2 <= dx) { err += dx; y += sy; } } return cells; }
function rectCells(a, b) { const cells = []; const minX = Math.min(a.x, b.x); const maxX = Math.max(a.x, b.x); const minY = Math.min(a.y, b.y); const maxY = Math.max(a.y, b.y); for (let y = minY; y <= maxY; y += 1) for (let x = minX; x <= maxX; x += 1) if (x === minX || x === maxX || y === minY || y === maxY) cells.push({ x, y }); return cells; }
function applyPaint(cell, tool = state.tool) {
  const old = cellAt(cell.x, cell.y); if (tool === 'eraser') { setCell(cell.x, cell.y, [...TRANSPARENT]); return; }
  if (tool === 'picker') { if (state.drawMode === 'height') setHeightInput(old[4]); else setColor(rgbaToHex(old)); selectTool('pencil'); return; }
  if (tool === 'pencil') setCell(cell.x, cell.y, state.drawMode === 'height' ? [...old.slice(0, 4), getHeightInput()] : [...colorToRgba(state.color), old[4]]);
}
function fillAt(start) {
  const target = cellAt(start.x, start.y); const replacement = state.drawMode === 'height' ? getHeightInput() : colorToRgba(state.color); const matches = (pixel) => state.drawMode === 'height' ? pixel[4] === target[4] : sameColor(pixel.slice(0, 4), target.slice(0, 4)); const queue = [start]; const seen = new Set();
  while (queue.length) { const cell = queue.pop(); const key = `${cell.x},${cell.y}`; if (seen.has(key) || !matches(cellAt(cell.x, cell.y))) continue; seen.add(key); const old = cellAt(cell.x, cell.y); setCell(cell.x, cell.y, state.drawMode === 'height' ? [...old.slice(0, 4), replacement] : [...replacement, old[4]]); if (cell.x > 0) queue.push({ x: cell.x - 1, y: cell.y }); if (cell.x < state.width - 1) queue.push({ x: cell.x + 1, y: cell.y }); if (cell.y > 0) queue.push({ x: cell.x, y: cell.y - 1 }); if (cell.y < state.height - 1) queue.push({ x: cell.x, y: cell.y + 1 }); }
}
function paintStart(event) { if (event.button === 2) { applyPaint(getCell(event), 'picker'); event.preventDefault(); return; } if (event.button !== 0) return; const cell = getCell(event); state.isDrawing = true; state.startCell = cell; canvas.setPointerCapture?.(event.pointerId); if (state.tool === 'fill') fillAt(cell); else if (state.tool !== 'line' && state.tool !== 'rect') applyPaint(cell); draw(); updateModel(); }
function paintMove(event) { const cell = getCell(event); document.getElementById('pointerX').textContent = String(cell.x).padStart(2, '0'); document.getElementById('pointerY').textContent = String(cell.y).padStart(2, '0'); if (state.isDrawing && (state.tool === 'pencil' || state.tool === 'eraser')) { applyPaint(cell); draw(); updateModel(); } }
function paintEnd(event) { if (!state.isDrawing) return; const cell = getCell(event); if (state.tool === 'line' || state.tool === 'rect') (state.tool === 'line' ? lineCells(state.startCell, cell) : rectCells(state.startCell, cell)).forEach((item) => applyPaint(item, 'pencil')); state.isDrawing = false; state.startCell = null; draw(); updateModel(); commitHistory(); }

function setColor(value) { state.color = normalizeColor(value); document.getElementById('colorInput').value = state.color.slice(0, 7); document.getElementById('hexInput').value = state.color.slice(0, 7); document.getElementById('hexValue').textContent = state.color.slice(0, 7); document.getElementById('colorPreview').style.setProperty('--current-color', state.color); document.querySelectorAll('.swatch').forEach((swatch) => swatch.classList.toggle('selected', normalizeColor(swatch.dataset.color) === state.color)); }
function setHeightInput(value) { const height = clampHeight(value); document.getElementById('heightRange').value = height; document.getElementById('heightValue').textContent = height; }
function getHeightInput() { return clampHeight(document.getElementById('heightRange').value); }
function selectTool(tool) { state.tool = tool; document.querySelectorAll('.tool-button').forEach((button) => button.classList.toggle('active', button.dataset.tool === tool)); updateUi(); }
function setDrawMode(mode) { state.drawMode = mode; document.querySelectorAll('.draw-mode').forEach((button) => button.classList.toggle('active', button.dataset.drawMode === mode)); stage.classList.toggle('height-mode', mode === 'height'); draw(); updateUi(); }
function updateUi() { document.getElementById('canvasSizeLabel').textContent = `${state.width} × ${state.height} px`; document.getElementById('zoomLabel').textContent = `${state.zoom}×`; document.getElementById('activeToolLabel').textContent = `${state.drawMode === 'height' ? '高度绘制' : '颜色绘制'} · ${toolNames[state.tool]}`; root.style.setProperty('--canvas-size', `${state.zoom * Math.min(state.width, state.height)}px`); updateHistoryButtons(); updateDirty(); }
function syncSizeInputs() { document.getElementById('widthInput').value = state.width; document.getElementById('heightInput').value = state.height; }
function resizeCanvas(width, height, preserve = false) { width = Math.max(4, Math.min(128, Number(width) || 32)); height = Math.max(4, Math.min(128, Number(height) || 32)); const old = state.pixels; const oldWidth = state.width; state.width = width; state.height = height; state.pixels = blankPixels(width, height); if (preserve) for (let y = 0; y < Math.min(height, Math.floor(old.length / oldWidth)); y += 1) for (let x = 0; x < Math.min(width, oldWidth); x += 1) state.pixels[cellIndex(x, y)] = [...old[y * oldWidth + x]]; state.zoom = Math.max(4, Math.min(24, Math.floor(512 / Math.max(width, height)))); syncSizeInputs(); draw(); updateModel(); updateUi(); }
function updateHistoryButtons() { document.getElementById('undoButton').disabled = state.historyIndex <= 0; document.getElementById('redoButton').disabled = state.historyIndex >= state.history.length - 1; }
function updateDirty() { document.getElementById('dirtyDot').classList.toggle('visible', state.dirty); }
function updatePixelCount() { document.getElementById('pixelCount').textContent = `${state.pixels.filter((pixel) => pixel[3] > 0).length} / ${state.width * state.height} 像素`; }
function updateLayerThumb() { /* retained as a rendering hook for future layers */ }
function showToast(message) { const toast = document.getElementById('toast'); toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('visible'), 2400); }
function updateModel() { const data = modelRenderer.update(currentDocument(), state.modelOptionsWithMode || { ...state.modelOptions, mode: state.geometry }); document.getElementById('activePixels').textContent = data.activePixels; document.getElementById('maxHeight').textContent = Math.round(data.maxHeight * 10) / 10; document.getElementById('triangleCount').textContent = data.triangles; document.getElementById('emptyModel').classList.toggle('hidden', data.activePixels > 0); }
function getFileName() { return document.getElementById('documentName').value.trim().replace(/[^\w\-\u4e00-\u9fa5]+/g, '-') || 'untitled-pixel'; }
function download(name, content, type) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
function exportJson() { download(`${getFileName()}.json`, JSON.stringify({ format: 'pixelfoundry-rgbah', version: 2, ...currentDocument() }, null, 2), 'application/json'); state.dirty = false; updateDirty(); showToast('已导出 RGBAH JSON'); }
function exportTxt() { const lines = ['PIXELFOUNDRY-RGBAH 2', `${state.width} ${state.height}`, '# 每行：R G B A Height']; state.pixels.forEach((pixel) => lines.push(pixel.join(' '))); download(`${getFileName()}.rgbah.txt`, lines.join('\n'), 'text/plain'); state.dirty = false; updateDirty(); showToast('已导出 RGBAH TXT'); }
function exportPng() { const off = document.createElement('canvas'); off.width = state.width; off.height = state.height; const offCtx = off.getContext('2d'); state.pixels.forEach((pixel, index) => { if (pixel[3]) { offCtx.fillStyle = `rgba(${pixel[0]},${pixel[1]},${pixel[2]},${pixel[3] / 255})`; offCtx.fillRect(index % state.width, Math.floor(index / state.width), 1, 1); } }); off.toBlob((blob) => { download(`${getFileName()}.png`, blob, 'image/png'); showToast('已导出 PNG'); }); }
async function importFile(file) { let documentData; if (file.type === 'image/png' || file.name.toLowerCase().endsWith('.png')) { const image = await new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = URL.createObjectURL(file); }); const width = Math.min(128, image.naturalWidth); const height = Math.min(128, image.naturalHeight); const off = document.createElement('canvas'); off.width = width; off.height = height; off.getContext('2d').drawImage(image, 0, 0, width, height); const values = off.getContext('2d').getImageData(0, 0, width, height).data; const pixels = []; for (let index = 0; index < values.length; index += 4) pixels.push([values[index], values[index + 1], values[index + 2], values[index + 3]]); documentData = normalizeDocument({ width, height, pixels }); } else if (file.name.toLowerCase().endsWith('.json')) documentData = normalizeDocument(JSON.parse(await file.text())); else documentData = parseRgbaText(await file.text()); state.width = documentData.width; state.height = documentData.height; state.pixels = documentData.pixels; state.history = [snapshot()]; state.historyIndex = 0; state.dirty = false; state.zoom = Math.max(4, Math.min(24, Math.floor(512 / Math.max(state.width, state.height)))); syncSizeInputs(); draw(); updateModel(); updateUi(); showToast(`已导入 ${state.width} × ${state.height} 画布`); }

canvas.addEventListener('pointerdown', paintStart); canvas.addEventListener('pointermove', paintMove); canvas.addEventListener('pointerup', paintEnd); canvas.addEventListener('pointercancel', paintEnd); canvas.addEventListener('contextmenu', (event) => event.preventDefault());
document.querySelectorAll('.tool-button').forEach((button) => button.addEventListener('click', () => selectTool(button.dataset.tool))); document.querySelectorAll('.draw-mode').forEach((button) => button.addEventListener('click', () => setDrawMode(button.dataset.drawMode)));
document.getElementById('heightRange').addEventListener('input', (event) => setHeightInput(event.target.value)); document.getElementById('heightLabels').addEventListener('change', (event) => { state.showHeightLabels = event.target.checked; draw(); });
document.getElementById('colorInput').addEventListener('input', (event) => setColor(event.target.value)); document.getElementById('hexInput').addEventListener('change', (event) => setColor(event.target.value)); document.querySelectorAll('.swatch').forEach((swatch) => swatch.addEventListener('click', () => setColor(swatch.dataset.color)));
document.getElementById('undoButton').addEventListener('click', undo); document.getElementById('redoButton').addEventListener('click', redo); document.getElementById('gridToggle').addEventListener('click', (event) => { state.grid = !state.grid; event.currentTarget.classList.toggle('active', state.grid); draw(); }); document.getElementById('centerButton').addEventListener('click', () => showToast('画布已居中')); document.getElementById('clearButton').addEventListener('click', () => { if (!state.pixels.some((pixel) => pixel[3] || pixel[4])) return; state.pixels = blankPixels(state.width, state.height); draw(); updateModel(); commitHistory(); showToast('画布已清空'); });
document.getElementById('zoomOut').addEventListener('click', () => { state.zoom = Math.max(4, state.zoom - 2); updateUi(); }); document.getElementById('zoomIn').addEventListener('click', () => { state.zoom = Math.min(32, state.zoom + 2); updateUi(); }); document.getElementById('fitButton').addEventListener('click', () => { state.zoom = Math.max(4, Math.min(24, Math.floor(Math.min(stage.clientWidth - 80, stage.clientHeight - 80) / Math.max(state.width, state.height)))); updateUi(); });
document.getElementById('resizeButton').addEventListener('click', () => { resizeCanvas(document.getElementById('widthInput').value, document.getElementById('heightInput').value, true); commitHistory(); showToast('画布尺寸已更新'); });
document.querySelectorAll('.geometry-button').forEach((button) => button.addEventListener('click', () => { state.geometry = button.dataset.geometry; document.querySelectorAll('.geometry-button').forEach((item) => item.classList.toggle('active', item === button)); updateModel(); }));
['pixelSize', 'heightScale', 'pixelGap', 'baseThickness'].forEach((id) => document.getElementById(id).addEventListener('input', (event) => { state.modelOptions[id === 'pixelSize' ? 'pixelSize' : id === 'heightScale' ? 'heightScale' : id === 'pixelGap' ? 'gap' : 'baseThickness'] = Number(event.target.value); updateModel(); })); document.getElementById('baseToggle').addEventListener('change', (event) => { state.modelOptions.base = event.target.checked; document.querySelector('.base-thickness-row').classList.toggle('enabled', event.target.checked); updateModel(); }); document.getElementById('resetView').addEventListener('click', () => modelRenderer.resetView());
document.getElementById('exportGlb').addEventListener('click', async () => { await exportGlb(modelRenderer.modelRoot, getFileName()); showToast('已导出 GLB'); }); document.getElementById('exportObj').addEventListener('click', () => { exportObj(modelRenderer.modelRoot, getFileName()); showToast('已导出 OBJ'); });
document.querySelectorAll('.mode-button').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.mode-button').forEach((item) => item.classList.toggle('active', item === button)); document.getElementById('workspace').classList.toggle('draw-only', button.dataset.workspace === 'draw'); }));
document.getElementById('newButton').addEventListener('click', () => document.getElementById('newModal').classList.add('open')); document.getElementById('closeModal').addEventListener('click', () => document.getElementById('newModal').classList.remove('open')); document.getElementById('cancelNew').addEventListener('click', () => document.getElementById('newModal').classList.remove('open')); document.getElementById('confirmNew').addEventListener('click', () => { resizeCanvas(document.getElementById('newWidth').value, document.getElementById('newHeight').value); state.history = [snapshot()]; state.historyIndex = 0; state.dirty = false; document.getElementById('newModal').classList.remove('open'); updateUi(); showToast('新画布已创建'); });
document.getElementById('openButton').addEventListener('click', () => document.getElementById('fileInput').click()); document.getElementById('fileInput').addEventListener('change', async (event) => { const file = event.target.files[0]; if (file) try { await importFile(file); } catch (error) { showToast(`导入失败：${error.message}`); } event.target.value = ''; });
document.getElementById('saveButton').addEventListener('click', () => { const menu = document.createElement('div'); menu.className = 'export-menu'; menu.innerHTML = '<button data-format="json">RGBAH JSON · 可编辑数据</button><button data-format="txt">RGBAH TXT · 纯文本</button><button data-format="png">PNG · 图片预览</button>'; Object.assign(menu.style, { position: 'fixed', right: '22px', top: '56px', zIndex: 30 }); document.body.appendChild(menu); menu.querySelectorAll('button').forEach((button) => button.addEventListener('click', () => { if (button.dataset.format === 'json') exportJson(); if (button.dataset.format === 'txt') exportTxt(); if (button.dataset.format === 'png') exportPng(); menu.remove(); })); setTimeout(() => document.addEventListener('pointerdown', (event) => { if (!menu.contains(event.target)) menu.remove(); }, { once: true }), 0); });
document.addEventListener('keydown', (event) => { const mod = event.ctrlKey || event.metaKey; if (mod && event.key.toLowerCase() === 'z') { event.preventDefault(); event.shiftKey ? redo() : undo(); } if (mod && event.key.toLowerCase() === 'y') { event.preventDefault(); redo(); } if (!mod && event.key.toLowerCase() === 'b') selectTool('pencil'); if (!mod && event.key.toLowerCase() === 'e') selectTool('eraser'); if (!mod && event.key.toLowerCase() === 'g') selectTool('fill'); if (!mod && event.key.toLowerCase() === 'i') selectTool('picker'); if (!mod && event.key.toLowerCase() === 'l') selectTool('line'); if (!mod && event.key.toLowerCase() === 'r') selectTool('rect'); });

state.pixels = blankPixels(state.width, state.height); state.history = [snapshot()]; state.historyIndex = 0; setColor(state.color); setHeightInput(1); draw(); updateModel(); updateUi(); setTimeout(() => document.getElementById('canvasHint').classList.add('visible'), 300); setTimeout(() => document.getElementById('canvasHint').classList.remove('visible'), 3200);
