document.write("<!DOCTYPE html>");
document.write("<html lang=\"zh\">");
document.write("  <head>");
document.write("    <meta charset=\"UTF-8\" \/>");
document.write("    <title>小幽灵盯着我的鼠标怎么办<\/title>");
document.write("    <style>");
document.write("      html,");
document.write("      body {");
document.write("        background: #28254c;");
document.write("        font-family: 'Ubuntu';");
document.write("      }");
document.write("      * {");
document.write("        box-sizing: border-box;");
document.write("      }");
document.write("      .box .box__ghost {");
document.write("        padding: 15px 25px 25px;");
document.write("        position: absolute;");
document.write("        left: 50%;");
document.write("        top: 30%;");
document.write("        transform: translate(-50%, -30%);");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(1) {");
document.write("        opacity: 0.2;");
document.write("        animation: shine 4s ease-in-out 3s infinite;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(1):before,");
document.write("      .box .box__ghost .symbol:nth-child(1):after {");
document.write("        content: '';");
document.write("        width: 12px;");
document.write("        height: 4px;");
document.write("        background: #fff;");
document.write("        position: absolute;");
document.write("        border-radius: 5px;");
document.write("        bottom: 65px;");
document.write("        left: 0;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(1):before {");
document.write("        transform: rotate(45deg);");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(1):after {");
document.write("        transform: rotate(-45deg);");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(2) {");
document.write("        position: absolute;");
document.write("        left: -5px;");
document.write("        top: 30px;");
document.write("        height: 18px;");
document.write("        width: 18px;");
document.write("        border: 4px solid;");
document.write("        border-radius: 50%;");
document.write("        border-color: #fff;");
document.write("        opacity: 0.2;");
document.write("        animation: shine 4s ease-in-out 1.3s infinite;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(3) {");
document.write("        opacity: 0.2;");
document.write("        animation: shine 3s ease-in-out 0.5s infinite;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(3):before,");
document.write("      .box .box__ghost .symbol:nth-child(3):after {");
document.write("        content: '';");
document.write("        width: 12px;");
document.write("        height: 4px;");
document.write("        background: #fff;");
document.write("        position: absolute;");
document.write("        border-radius: 5px;");
document.write("        top: 5px;");
document.write("        left: 40px;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(3):before {");
document.write("        transform: rotate(90deg);");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(3):after {");
document.write("        transform: rotate(180deg);");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(4) {");
document.write("        opacity: 0.2;");
document.write("        animation: shine 6s ease-in-out 1.6s infinite;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(4):before,");
document.write("      .box .box__ghost .symbol:nth-child(4):after {");
document.write("        content: '';");
document.write("        width: 15px;");
document.write("        height: 4px;");
document.write("        background: #fff;");
document.write("        position: absolute;");
document.write("        border-radius: 5px;");
document.write("        top: 10px;");
document.write("        right: 30px;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(4):before {");
document.write("        transform: rotate(45deg);");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(4):after {");
document.write("        transform: rotate(-45deg);");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(5) {");
document.write("        position: absolute;");
document.write("        right: 5px;");
document.write("        top: 40px;");
document.write("        height: 12px;");
document.write("        width: 12px;");
document.write("        border: 3px solid;");
document.write("        border-radius: 50%;");
document.write("        border-color: #fff;");
document.write("        opacity: 0.2;");
document.write("        animation: shine 1.7s ease-in-out 7s infinite;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(6) {");
document.write("        opacity: 0.2;");
document.write("        animation: shine 2s ease-in-out 6s infinite;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(6):before,");
document.write("      .box .box__ghost .symbol:nth-child(6):after {");
document.write("        content: '';");
document.write("        width: 15px;");
document.write("        height: 4px;");
document.write("        background: #fff;");
document.write("        position: absolute;");
document.write("        border-radius: 5px;");
document.write("        bottom: 65px;");
document.write("        right: -5px;");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(6):before {");
document.write("        transform: rotate(90deg);");
document.write("      }");
document.write("      .box .box__ghost .symbol:nth-child(6):after {");
document.write("        transform: rotate(180deg);");
document.write("      }");
document.write("      .box .box__ghost .box__ghost-container {");
document.write("        background: #fff;");
document.write("        width: 100px;");
document.write("        height: 100px;");
document.write("        border-radius: 100px 100px 0 0;");
document.write("        position: relative;");
document.write("        margin: 0 auto;");
document.write("        animation: upndown 3s ease-in-out infinite;");
document.write("      }");
document.write("      .box .box__ghost .box__ghost-container .box__ghost-eyes {");
document.write("        position: absolute;");
document.write("        left: 50%;");
document.write("        top: 45%;");
document.write("        height: 12px;");
document.write("        width: 70px;");
document.write("      }");
document.write("      .box .box__ghost .box__ghost-container .box__ghost-eyes .box__eye-left {");
document.write("        width: 12px;");
document.write("        height: 12px;");
document.write("        background: #332f63;");
document.write("        border-radius: 50%;");
document.write("        margin: 0 10px;");
document.write("        position: absolute;");
document.write("        left: 0;");
document.write("      }");
document.write("      .box .box__ghost .box__ghost-container .box__ghost-eyes .box__eye-right {");
document.write("        width: 12px;");
document.write("        height: 12px;");
document.write("        background: #332f63;");
document.write("        border-radius: 50%;");
document.write("        margin: 0 10px;");
document.write("        position: absolute;");
document.write("        right: 0;");
document.write("      }");
document.write("      .box .box__ghost .box__ghost-container .box__ghost-bottom {");
document.write("        display: flex;");
document.write("        position: absolute;");
document.write("        top: 100%;");
document.write("        left: 0;");
document.write("        right: 0;");
document.write("      }");
document.write("      .box .box__ghost .box__ghost-container .box__ghost-bottom div {");
document.write("        flex-grow: 1;");
document.write("        position: relative;");
document.write("        top: -10px;");
document.write("        height: 20px;");
document.write("        border-radius: 100%;");
document.write("        background-color: #fff;");
document.write("      }");
document.write("      .box");
document.write("        .box__ghost");
document.write("        .box__ghost-container");
document.write("        .box__ghost-bottom");
document.write("        div:nth-child(2n) {");
document.write("        top: -12px;");
document.write("        margin: 0 0px;");
document.write("        border-top: 15px solid #332f63;");
document.write("        background: transparent;");
document.write("      }");
document.write("      .box .box__ghost .box__ghost-shadow {");
document.write("        height: 20px;");
document.write("        box-shadow: 0 50px 15px 5px #3b3769;");
document.write("        border-radius: 50%;");
document.write("        margin: 0 auto;");
document.write("        animation: smallnbig 3s ease-in-out infinite;");
document.write("      }");
document.write("      @keyframes upndown {");
document.write("        0% {");
document.write("          transform: translateY(5px);");
document.write("        }");
document.write("        50% {");
document.write("          transform: translateY(15px);");
document.write("        }");
document.write("        100% {");
document.write("          transform: translateY(5px);");
document.write("        }");
document.write("      }");
document.write("      @keyframes smallnbig {");
document.write("        0% {");
document.write("          width: 90px;");
document.write("        }");
document.write("        50% {");
document.write("          width: 100px;");
document.write("        }");
document.write("        100% {");
document.write("          width: 90px;");
document.write("        }");
document.write("      }");
document.write("      @keyframes shine {");
document.write("        0% {");
document.write("          opacity: 0.2;");
document.write("        }");
document.write("        25% {");
document.write("          opacity: 0.1;");
document.write("        }");
document.write("        50% {");
document.write("          opacity: 0.2;");
document.write("        }");
document.write("        100% {");
document.write("          opacity: 0.2;");
document.write("        }");
document.write("      }");
document.write("    <\/style>");
document.write("  <\/head>");
document.write("  <body>");
document.write("    <div class=\"box\">");
document.write("      <div class=\"box__ghost\">");
document.write("        <div class=\"symbol\"><\/div>");
document.write("        <div class=\"symbol\"><\/div>");
document.write("        <div class=\"symbol\"><\/div>");
document.write("        <div class=\"symbol\"><\/div>");
document.write("        <div class=\"symbol\"><\/div>");
document.write("        <div class=\"symbol\"><\/div>");
document.write("        <div class=\"box__ghost-container\">");
document.write("          <div class=\"box__ghost-eyes\">");
document.write("            <div class=\"box__eye-left\"><\/div>");
document.write("            <div class=\"box__eye-right\"><\/div>");
document.write("          <\/div>");
document.write("          <div class=\"box__ghost-bottom\">");
document.write("            <div><\/div>");
document.write("            <div><\/div>");
document.write("            <div><\/div>");
document.write("            <div><\/div>");
document.write("            <div><\/div>");
document.write("          <\/div>");
document.write("        <\/div>");
document.write("        <div class=\"box__ghost-shadow\"><\/div>");
document.write("      <\/div>");
document.write("    <\/div>");
document.write("    <script>");
document.write("      var pageX = document.documentElement.scrollWidth;");
document.write("      var pageY = document.documentElement.scrollHeight;");
document.write("      var mouseY = 0;");
document.write("      var mouseX = 0;");
document.write("      document.addEventListener('mousemove', function (event) {");
document.write("        mouseY = event.pageY;");
document.write("        var yAxis = ((pageY \/ 2 - mouseY) \/ pageY) * 300;");
document.write("        mouseX = event.pageX \/ -pageX;");
document.write("        var xAxis = -mouseX * 100 - 100;");
document.write("        var boxGhostEyes = document.querySelector('.box__ghost-eyes');");
document.write("        boxGhostEyes.style.transform = `translate(${xAxis}%,${-yAxis}%)`;");
document.write("      });");
document.write("    <\/script>");
document.write("  <\/body>");
document.write("<\/html>");
document.write("");
